# Generated by Django 3.0.7 on 2020-08-05 15:12

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code_bill', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('path', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name_distributor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date_invoice', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total_money', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(blank=True, default=None, max_length=100)),
                ('url', models.ImageField(upload_to=api.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('price', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total_price', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tax', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('money_tax', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='InfoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('text', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Image')),
            ],
        ),
        migrations.AddField(
            model_name='distributor',
            name='id_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
    ]
