# Generated by Django 3.0.7 on 2020-08-06 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200805_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
