# Generated by Django 3.0.7 on 2020-08-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_shop',
            new_name='id_distributor',
        ),
    ]
