# Generated by Django 4.2.11 on 2024-05-14 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('price', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total_price', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tax', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tax_money', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
                ('address', models.CharField(blank=True, default=None, max_length=100)),
                ('tax_code', models.CharField(blank=True, default=None, max_length=100)),
                ('phone', models.CharField(blank=True, default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_buyer', models.CharField(blank=True, default=None, max_length=100)),
                ('company', models.CharField(blank=True, default=None, max_length=100)),
                ('address', models.CharField(blank=True, default=None, max_length=100)),
                ('phone', models.CharField(blank=True, default=None, max_length=100)),
                ('tax_code', models.CharField(blank=True, default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_of_lading_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code_bill', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('image_path', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('form_of_payment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date_invoice', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total_money', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total_tax', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('distributor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlhd.distributor')),
                ('purchaser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlhd.purchaser')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail_invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlhd.detailinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='detailinvoice',
            name='tax_invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlhd.taxinvoice'),
        ),
    ]
