# Generated by Django 3.2 on 2024-05-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlhd', '0002_detailinvoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlhd.product'),
        ),
        migrations.AlterField(
            model_name='detailinvoice',
            name='price',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='detailinvoice',
            name='total_price',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Đang chờ', 'Pending'), ('Xác nhận đơn hàng', 'Order Confirmed'), ('Đang giao hàng', 'Delivering'), ('Đã giao hàng', 'Delivered')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordersdetail',
            name='price',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
    ]
